### ISSUE TITLE
setup.py requires cython/numpy

### ISSUE THREAD

**Issue by scarecrow1123** [ludlows/python-pesq#10]
It would be great if installing this package installs the requirements automatically, without having to install cython/numpy manually.

**Comment by ludlows** [comment]
hi @scarecrow1123 ,
thanks for your contribution?
have you tested the modified code on linux and windows platforms?

**Comment by scarecrow1123** [comment]
This was tested in Ubuntu 19.10 and it works fine. I'm afraid I wouldn't be able to test it on a Windows machine. Thanks!

**Comment by schmiph2** [comment]
@ludlows are you considering to merge the PR of @scarecrow1123 #9  ? would be great!
