### ISSUE TITLE
Raise exception in python instead of calling exit(1) in C function

### ISSUE THREAD

**Issue by linzwatt** [ludlows/python-pesq#11]
On this line in the C code:
https://github.com/ludlows/python-pesq/blob/50591b2635a786c7f88446186eeda25bd78cf914/pesq/pesqmod.c#L947

`exit(1)` is called, which immediately terminates any python code running without warning, no exception or anything. Would you be able to return a flag to the python wrapper, and raise an Exception there? Then it could be caught by a try except block.

I am using this in an automated setting, so it is not always certain the audio will be valid for the pesq library, if an exception was raised, I can skip that audio and keep running my system

**Comment by ludlows** [comment]
Thanks for your suggestions. 
please using [(this version)](https://github.com/samedii/python-pesq) for now. 
I plan to enable this code to raise different errors and support for `try-except` behavior in several months.

**Comment by linzwatt** [comment]
Thanks for the suggestion 😊 I should have looked at the open PRs before posting an issue
