### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mpariente** [ludlows/python-pesq#14]
Could we please get a new PyPI release without the need to install numpy and Cython before installing python-pesq, that would be really great !

Thanks

**Comment by ludlows** [comment]
Hi @mpariente ,

thanks for your  suggestions. 
I will update the latest release on PyPi before next Monday. 
Have a Nice Day!

**Comment by RomaVis** [comment]
Dear @ludlows,

Would it be possible to get it on PyPi any time soon? I guess version number can also be increased ;-)

**Comment by ludlows** [comment]
hi @RomaVis ,
yes. it should be soon. 
i cannot access my personal laptop during a new program. 
i am sorry for this delay.

**Comment by jonashaag** [comment]
Hey, is there a way to make the update? Can I help you in some way?

**Comment by mpariente** [comment]
Yeah, that would be very practical to be able to skip the numpy/cython install before installing anything that depends on pesq

**Comment by ludlows** [comment]
Thanks for your reminders. 

the latest version has been uploaded on https://pypi.org/manage/project/pesq/release/0.0.2/

**Comment by ludlows** [comment]
I have updated the version on PyPi to support to installing dependents automatically.
