### ISSUE TITLE
Segmentation fault(core dumped)

### ISSUE THREAD

**Issue by sreejith-ratnakumar** [ludlows/python-pesq#15]
I was trying to run the script with a 25 minute long audio and I got segmentation fault. Everything is fine when I checked with a 5 second audio

**Comment by ludlows** [comment]
The code needs to allocate memory for the long audio. So could you split the entire long audio into several shorter ones ?
Thanks&nbsp;





------------------ Original ------------------

**Comment by sreejith-ratnakumar** [comment]
ok sure thanks

**Comment by ludlows** [comment]
the issue seems has been solved.
