### ISSUE TITLE
Stack smashing if input too long

### ISSUE THREAD

**Issue by jonashaag** [ludlows/python-pesq#18]
I have an example where PESQ aborts with a stack smashing message. I guess it's because I accidentally put in a very long audio snippet (~120s). I'm happy submit a PR but I don't know what's a sensible maximum length value

**Comment by ludlows** [comment]
it depends the sampling rate and memory on the hardware. 
the maximum length value is not necessary once a good error-handling mechanism was established, in my opinion.

**Comment by ludlows** [comment]
anyone can reopen this issue if an update was given.
