### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by CXMANDTXW** [ludlows/python-pesq#20]
When I use  `from pesq import pesq`.
I got an error: cannot import name 'pesq' from 'pesq'.
python:3.7.   pesq-0.0.2

**Comment by ludlows** [comment]
please change your workspace to `Desktop` or `Downloads` and try again.

**Comment by CXMANDTXW** [comment]
The problem is solved perfectly.Thank you.

**Comment by DJEddyking** [comment]
> please change your workspace to `Desktop` or `Downloads` and try again.

sorry, can you tell me what that means? I have the same problem

**Comment by ludlows** [comment]
try to type the bash command below:
```bash
cd ~/desktop
```
and then run you code here
