### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by shishichang** [ludlows/python-pesq#21]
I compute two audio signals:
 clean: [[-0.05551147 -0.05551147 -0.05593872 -0.05615234 -0.05548096 -0.05499268 -0.05484009 -0.05435181 -0.05456543 -0.05557251]]
noisy: [[0.13543701 0.2192688  0.2921753  0.3097229  0.30447388 0.29248047 0.2775879  0.22662354 0.1618042  0.05249023]]

why the result of pesq  is  -1 in 'nb' mode?

**Comment by ludlows** [comment]
your inputs are illegal and caused an error in `pesq` code. 

you may use real audio signals and try again

**Comment by redmist328** [comment]
Hi, @ludlows . I wonder what is the mening of 'illegal' for inputs.
