### ISSUE TITLE
No module named 'pesq.cypesq'

### ISSUE THREAD

**Issue by kadir-gunel** [ludlows/python-pesq#24]
Hello, 
Installed from source via virtualenv with pip3. But when trying to import get `ModuleNotFoundError`. I installed cython, and numpy.

```python

>>> from pesq import pesq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kg/github/python-pesq/pesq/__init__.py", line 6, in <module>
    from .cypesq import cypesq
ModuleNotFoundError: No module named 'pesq.cypesq'

No module named 'pesq.cypesq'

```

B.R.

**Comment by ludlows** [comment]
check this issue https://github.com/ludlows/python-pesq/issues/20

let me know if you still cannot solve it

**Comment by kadir-gunel** [comment]
tbh solution for this (#20 ) is the strangest solution that I have ever encountered. 

Thank you

**Comment by miaoyatai** [comment]
I switched the workspace to the desktop and tried, but the problem was the same.

**Comment by ludlows** [comment]
@miaoyatai 
hi, could you give more details about this error like your repository structure?
you could also using "pip install https://github.com/ludlows/python-pesq/archive/refs/tags/v0.0.3.zip "this code directly.

**Comment by Ahmad1kraidy** [comment]
@ludlows I use Google Colab and I cannot change the work environment location because Colab deals with Drive. I need your help to solve the problem, which is that it does not recognize the cypesq model. What is the solution?
