### ISSUE TITLE
python2.7.6  pip install failed

### ISSUE THREAD

**Issue by LexiYIN** [ludlows/python-pesq#26]
Hi, 
I got the problem as followed when I install the pesq using python2.7' pip:
```
$pip install .
Processing /student/home/yll/MetricGAN/python-pesq
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home2/tmp/pip-UYvuSf-build/setup.py", line 32, in <module>
        language="c")
      File "/home2/tmp/pip-UYvuSf-build/setup.py", line 15, in __init__
        super().__init__(*args, **kwargs)
    TypeError: super() takes at least 1 argument (0 given)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home2/tmp/pip-UYvuSf-build/
```

By the way, I also try it on python3.6 and successefully, but why failed on python2?
Thank you very much.

**Comment by ludlows** [comment]
the 0-argument syntax is specific to Python 3. 
You could adapt the code to fit with Python 2 in the following manner. 
`python
class CyPesqExtension(Extension):
    def __init__(self, *args, **kwargs):
        self._include = []
        super(CyPesqExtension, self).__init__(*args, **kwargs)

    @property
    def include_dirs(self):
        import numpy
        return self._include + [numpy.get_include()]

    @include_dirs.setter
    def include_dirs(self, dirs):
        self._include = dirs
`
I saw your were trying to use this in a tensorflow project, which relates to speech enhancement . 
It is interesting to see such applications using speech metrics in deep learning become more and more popular.
