### ISSUE TITLE
Processing error!

### ISSUE THREAD

**Issue by nisanaryal** [ludlows/python-pesq#28]
I faced this problem and could not find the solution in the issue section. So, this issue is for the users who will get stuck in this issue in the future. 
Apparently, this is caused by an exception called "No utterances detected", which is caused when the reference sound is nearly silent (reference and solution: Note section of  https://github.com/samedii/python-pesq).

Solution as of https://github.com/samedii/python-pesq , which worked for me.

```python
from pesq import PESQError

SAMPLE_RATE = 16000
silent_ref = np.zeros(16000)
deg = np.random.randn(16000)
try:
    pesq(SAMPLE_RATE, silent_ref, deg, 'wb')
except PESQError as e:
    print(e)
```

This will escape the sound file which is causing the exception but will not terminate the program.

**Comment by ludlows** [comment]
you could enable the error-handling behavior using the latest code on `dev` branch. 
and the method to enable it is listed on README.
