### ISSUE TITLE
ImportError, please help

### ISSUE THREAD

**Issue by RXAldreezee** [ludlows/python-pesq#29]
Hi, I already installed the python-pesq, when I was about to run, it shows an error message:

(venv) al@al-VirtualBox:~/Downloads/RNNoise_Wrapper-master$ python3 sepm.py 
Traceback (most recent call last):
  File "sepm.py", line 4, in <module>
    from pesq import PesqError
ImportError: cannot import name 'PesqError' from 'pesq' (/home/al/Downloads/RNNoise_Wrapper-master/venv/lib/python3.8/site-packages/pesq/__init__.py)

I already did #24 but didn't work. I also created a virtual environment, still doesn't work. Please help.

**Comment by ludlows** [comment]
thanks for using this code.

have you solved it?
or could you give more details about the error like the directory struture?

**Comment by RXAldreezee** [comment]
Unfortunately it didn't. I used this [https://github.com/schmiph2/pysepm](url) instead.

**Comment by ludlows** [comment]
thanks for your reply. 
I close this issue but anyone can open it if necessary.

**Comment by ludlows** [comment]
I close this issue but anyone can open it if necessary.
