### ISSUE TITLE
exits unexpectedly for large inputs

### ISSUE THREAD

**Issue by JHarri16** [ludlows/python-pesq#30]
As the title says, it exits unexpectedly with nominally large array inputs (I  haven't been able to bound the size at which this occurs).
A 30 second window at 16 KHz (480,000 samples) seems to work, and is enough for a provisional score, however the STOI metric currently in use accepts the full array without issue.
If it is of any use, the exit code is -1073740791 (0xC0000409)

**Comment by ludlows** [comment]
the error seems due to allocating a huge memory beyond the system limit.
