### ISSUE TITLE
The Error handling version 0.0.3 is not available in pip

### ISSUE THREAD

**Issue by quancs** [ludlows/python-pesq#31]
Hi, guys, thank you for your great works.

I know you provided the version 0.0.3 zip file. But, it would be nicer if you can provide the 0.0.3 version for the pip users.

**Comment by ludlows** [comment]
thanks for your suggestion. let me do this in the next week. 
after getting it done, I will close this issue.

**Comment by ludlows** [comment]
The latest version is on https://pypi.org/project/pesq/0.0.3/

**Comment by quancs** [comment]
> 
> 
> The latest version is on https://pypi.org/project/pesq/0.0.3/

Great! Thank you!
