### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by quancs** [ludlows/python-pesq#32]
王老师，您好，打扰了。
您的这个pesq包做得非常的好，是pesq包里面封装得最好的，目前我也正在使用使用您的包。
现在我遇到的问题就是，如果需要使用pesq的话，我需要自己再进行一次封装，来使得pesq可以适应[pytorch-lightning](https://github.com/PyTorchLightning/pytorch-lightning)这个框架。
因此，希望您将pesq搬到[TorchMetrics](https://github.com/PyTorchLightning/metrics)，不知您是否有时间！

**Comment by ludlows** [comment]
thanks for your suggestion. 
I am ok to help.
But I have seen your pull request for adding `pesq` into `TorchMetrics`. 
Actually you can continue this work.

**Comment by quancs** [comment]
Em... Yeah, I have given a pull request... But my pull request uses `pesq` as a dependency, which will make the `TorchMetric` more and more complicated when more metrics are implemented. Thus, it would be better that you can integrate the source code of `pesq` into `TorchMetric`.

**Comment by ludlows** [comment]
@quancs 
thanks for your reply.
do you mean that I need to inject the `c` source code of `pesq` into `TorchMetric` ?

**Comment by ludlows** [comment]
please reopen it if you wanna discuss more

**Comment by quancs** [comment]
> 
> 
> @quancs
> thanks for your reply.
> do you mean that I need to inject the `c` source code of `pesq` into `TorchMetric` ?

@ludlows 
Yeah... Are you willing to do this job? It's OK if not.
