### ISSUE TITLE
install problem on mac (error: command 'gcc' failed with exit status 1)

### ISSUE THREAD

**Issue by theyoungkwon** [ludlows/python-pesq#33]
Hi I've tried to install "pesq" through pip and also from the source code. 
But in both cases, I encountered an error (command 'gcc' failed with exit status 1). I have installed cython and my laptop's OS is Mac OS Big Sur v11.3. 

I'm wondering if the pesq package does not work on mac OS... or is there any other problem? Please let me know.

Here's an error message below.

$ pip3 install pesq==0.0.3
Collecting pesq==0.0.3
  Using cached pesq-0.0.3.tar.gz (35 kB)
Building wheels for collected packages: pesq
  Building wheel for pesq (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ydkwon/miniconda3/envs/py38/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/setup.py'"'"'; __file__='"'"'/private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-wheel-n93r4ojz
       cwd: /private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/
  Complete output (33 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/cypesq.pyx -> build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/pesq.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/pesqio.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/pesqpar.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/dsp.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/pesqmain.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/dsp.c -> build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/pesqdsp.c -> build/lib.macosx-10.9-x86_64-3.8/pesq
  copying pesq/pesqmod.c -> build/lib.macosx-10.9-x86_64-3.8/pesq
  running build_ext
  cythoning pesq/cypesq.pyx to pesq/cypesq.c
  /private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/.eggs/Cython-0.29.24-py3.8-macosx-10.9-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/pesq/cypesq.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'cypesq' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/pesq
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ydkwon/miniconda3/envs/py38/include -arch x86_64 -I/Users/ydkwon/miniconda3/envs/py38/include -arch x86_64 -Ipesq -I/Users/ydkwon/miniconda3/envs/py38/lib/python3.8/site-packages/numpy/core/include -I/Users/ydkwon/miniconda3/envs/py38/lib/python3.8/site-packages/numpy/core/include -I/Users/ydkwon/miniconda3/envs/py38/include/python3.8 -c pesq/cypesq.c -o build/temp.macosx-10.9-x86_64-3.8/pesq/cypesq.o
  In file included from /usr/local/Cellar/gcc@4.9/4.9.4_2/lib/gcc/4.9/gcc/x86_64-apple-darwin17.7.0/4.9.4/include-fixed/syslimits.h:7:0,
                   from /usr/local/Cellar/gcc@4.9/4.9.4_2/lib/gcc/4.9/gcc/x86_64-apple-darwin17.7.0/4.9.4/include-fixed/limits.h:34,
                   from /Users/ydkwon/miniconda3/envs/py38/include/python3.8/Python.h:11,
                   from pesq/cypesq.c:6:
  /usr/local/Cellar/gcc@4.9/4.9.4_2/lib/gcc/4.9/gcc/x86_64-apple-darwin17.7.0/4.9.4/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pesq
  Running setup.py clean for pesq
Failed to build pesq
Installing collected packages: pesq
    Running setup.py install for pesq ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ydkwon/miniconda3/envs/py38/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/setup.py'"'"'; __file__='"'"'/private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-record-1_t5nm25/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ydkwon/miniconda3/envs/py38/include/python3.8/pesq
         cwd: /private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/
    Complete output (31 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/cypesq.pyx -> build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/pesq.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/pesqio.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/pesqpar.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/dsp.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/pesqmain.h -> build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/dsp.c -> build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/pesqdsp.c -> build/lib.macosx-10.9-x86_64-3.8/pesq
    copying pesq/pesqmod.c -> build/lib.macosx-10.9-x86_64-3.8/pesq
    running build_ext
    skipping 'pesq/cypesq.c' Cython extension (up-to-date)
    building 'cypesq' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/pesq
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ydkwon/miniconda3/envs/py38/include -arch x86_64 -I/Users/ydkwon/miniconda3/envs/py38/include -arch x86_64 -Ipesq -I/Users/ydkwon/miniconda3/envs/py38/lib/python3.8/site-packages/numpy/core/include -I/Users/ydkwon/miniconda3/envs/py38/lib/python3.8/site-packages/numpy/core/include -I/Users/ydkwon/miniconda3/envs/py38/include/python3.8 -c pesq/cypesq.c -o build/temp.macosx-10.9-x86_64-3.8/pesq/cypesq.o
    In file included from /usr/local/Cellar/gcc@4.9/4.9.4_2/lib/gcc/4.9/gcc/x86_64-apple-darwin17.7.0/4.9.4/include-fixed/syslimits.h:7:0,
                     from /usr/local/Cellar/gcc@4.9/4.9.4_2/lib/gcc/4.9/gcc/x86_64-apple-darwin17.7.0/4.9.4/include-fixed/limits.h:34,
                     from /Users/ydkwon/miniconda3/envs/py38/include/python3.8/Python.h:11,
                     from pesq/cypesq.c:6:
    /usr/local/Cellar/gcc@4.9/4.9.4_2/lib/gcc/4.9/gcc/x86_64-apple-darwin17.7.0/4.9.4/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                                                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ydkwon/miniconda3/envs/py38/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/setup.py'"'"'; __file__='"'"'/private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-install-fxqt3zzv/pesq_f54ed1f751c64d17bc7d06d1701a2b47/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zz/mkr3s_81101_rh7kxcgvf7l80000gn/T/pip-record-1_t5nm25/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ydkwon/miniconda3/envs/py38/include/python3.8/pesq Check the logs for full command output.

Thank you!

**Comment by ludlows** [comment]
please check this link : https://stackoverflow.com/questions/30877659/fatal-error-limits-h-no-such-file-or-directory 
it should help.

**Comment by ludlows** [comment]
please reopen it if you wanna discuss more
