### ISSUE TITLE
Processing error!

### ISSUE THREAD

**Issue by LexiYIN** [ludlows/python-pesq#36]
Hello,
    It seems to raises "Processing error!" randomly when use the function and I can not figure it out, please give some help. Thank you very much.

**Comment by ludlows** [comment]
hi,
it would be better for anyone to help if you can provide the inputs and detailed error messages.
feel free to reopen it if you wanna discuss more.

**Comment by itz-vp** [comment]
![image](https://user-images.githubusercontent.com/100348383/187898260-e2dd12b5-49c6-4e58-9a5b-ec51bfd991ca.png)

Am also facing the same issue, Any idea why this happens ?
