### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by samhookecc** [ludlows/python-pesq#4]
Thank you @ludlows for creating this Python package!

I've noticed that in the `setup.py` file this package is marked as MIT licensed. However, to make this more apparent, please could you add a `LICENSE` file into the repo? GitHub has some useful information on this process:

https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by ludlows** [comment]
thanks. 
The license file has been added to the project.

**Comment by samhookecc** [comment]
Super, thank you very much for the fast response!
